# Generated by Django 6.0.2 on 2026-04-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Parcelle', max_length=200)),
                ('score', models.FloatField(default=0.5)),
                ('geometry_geojson', models.JSONField(blank=True, default=dict)),
                ('latitude', models.FloatField(default=46.23)),
                ('longitude', models.FloatField(default=7.36)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parcelle',
                'verbose_name_plural': 'Parcelles',
            },
        ),
    ]
